### PR TITLE
Replaced renamed pep8 with pycodestyle and added install dependency

### PR DESCRIPTION
**Pull request by ferraith**
The pep8 module was renamed to pycodestyle. flake8 already switched to pycodestyle 2.0.0. Because of that using flake8 and flake8-todo results in a dependency glitch. I also added a install dependency on pycodestyle. Until now this dependency was only indirectly given because flake8 had a dependency on pep8.

### CODE REVIEW

**Comment by schlamar** [comment]
Thanks. Can you please pin the dependency as flake8 is doing (`'pycodestyle >= 2.0, < 2.1'`).

**Comment by ferraith** [comment]
Done!

**Comment by hvelarde** [comment]
any chance of getting this merged and having a new release of the package?

**Comment by schlamar** [comment]
Yes, I'll try to find time for a release at the weekend.

**Comment by schlamar** [comment]
Thanks!

**Pull request merged**
